name: Build & deploys

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
# Disable deployment until everything else works
#      - name: GitHub Pages Deploy
#        uses: maxheld83/ghpages@v0.2.1
#        env:
#          BUILD_DIR: 'dist/'
