name: Upgrade dependencies

on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          version: '12.x'
      - name: Check for outdated dependencies
        run: npm outdated
